### ISSUE TITLE
How resolve EXE_in_LNK false positive on my project

### ISSUE THREAD

**Issue by FrenkyDema** [bartblaze/Yara-rules#11]
Sorry for this question a little out of context, but I would like to understand how to fix errors found as EXE_in_LNK by Yara;
### This is the role in my _.github/workflows/rules.yar_ :
```
rule EXE_in_LNK
{
    meta:
        id = "3SSZmnnXU0l4qoc9wubdhN"
        fingerprint = "f169fab39da34f827cdff5ee022374f7c1cc0b171da9c2bb718d8fee9657d7a3"
        version = "1.0"
        creation_date = "2020-01-01"
        first_imported = "2021-12-30"
        last_modified = "2021-12-30"
        status = "RELEASED"
        sharing = "TLP:WHITE"
        source = "BARTBLAZE"
        author = "@bartblaze"
        description = "Identifies executable artefacts in shortcut (LNK) files."
        category = "INFO"

    strings:
        $ = ".exe" ascii wide nocase
        $ = ".dll" ascii wide nocase
        $ = ".scr" ascii wide nocase
        $ = ".pif" ascii wide nocase
        $ = "This program" ascii wide nocase
        $ = "TVqQAA" ascii wide nocase

    condition:
        isLNK and any of them
}
```
### This is the error detected by **VirusTotal YARA-CI**
![image](https://user-images.githubusercontent.com/67586090/194705278-d0ed96aa-3777-417f-b244-0f3ae2c300f7.png)

How do I solve this problem detected in my project?

**Comment by bartblaze** [comment]
Hi FrenkyDema,

It's not really clear what you want to achieve - do you want to avoid that rule running on VirusTotal? 

If so, add it to the list to be ignored as I've done similarly in the yara-ci.yml file:
https://github.com/bartblaze/Yara-rules/blob/master/.yara-ci.yml

**Comment by FrenkyDema** [comment]
Hi, thanks for the reply;
In specific I would like to solve this error so that it is no longer detected by VirusTotal

**Comment by bartblaze** [comment]
Hi,

The rule you mention above is part of the Generic Yara rule set - refer to the following:
https://github.com/bartblaze/Yara-rules#help-a-generic-rule-is-hitting-my-software

If you do not want this to appear again in VT, add it to the Ignore list, or comment the Yara rule so it is not active.

**Comment by FrenkyDema** [comment]
Hi,
In particular, I would not like to deactivate the rule but try to solve the problem that makes it trigger if it is possible;
Thanks

**Comment by bartblaze** [comment]
Hi,

The rule is expected to have several False Positives - that's why it's a generic rule 😄 However, you're likely to reduce this rate a lot by removing this line:
`$ = ".exe" ascii wide nocase`

Let me know how that worked out.

**Comment by deMartiniFrancesco** [comment]
Hi,
So this rule is triggered when it detects some problem form my app code, right?

_This is my second account_

**Comment by bartblaze** [comment]
Hi,

The rule does exactly what it says: Identifies executable artefacts in shortcut (LNK) files.

As it's a generic rule, it can hit even on innocent shortcut files - that's why it's a generic rule. You can tweak the rule further until it doesn't hit, but that also defeats the purpose. 😄
