### ISSUE TITLE
Be more specific with the PyInstaller rule?

### ISSUE THREAD

**Issue by LuCeHe** [bartblaze/Yara-rules#14]
Hi,

I was wondering if you can change the rule that detects anything created with pyinstaller as malware to something that is more specific and more likely to really be malware. I think your rules became popular, and as a consequence now nobody can use pyinstaller to build an exe anymore. If you want to see people having troubles creating exes with pyinstaller check [here](https://stackoverflow.com/questions/43777106/program-made-with-pyinstaller-now-seen-as-a-trojan-horse-by-avg), [here](https://python.plainenglish.io/pyinstaller-exe-false-positive-trojan-virus-resolved-b33842bd3184) or [here](https://www.reddit.com/r/antivirus/comments/nlubcn/installing_pyinstaller_windows_antivirus_detecs/).

Have a good day,
Luca

**Comment by bartblaze** [comment]
Hi Luca,

Thanks for the feedback. Do read: https://github.com/bartblaze/Yara-rules?tab=readme-ov-file#help-a-generic-rule-is-hitting-my-software

That said, I do hear you, so I've updated the "category" and it will now specifically state INFO. In addition, the description has been updated, adding "This rule by itself does NOT necessarily mean the detected file is malicious."

As an FYI, I do not control what any of the antivirus and other engines are reporting on VirusTotal. If there is a (generic) hit of them on your software, you'll need to reach out to them individually.
