### ISSUE TITLE
VirusTotal false positive

### ISSUE THREAD

**Issue by Mouchoir** [bartblaze/Yara-rules#3]
Hello,

It seems like your rules causes false positives for a few antivirus in [VirusTotal (see link)](https://www.virustotal.com/gui/file/421cb704de82d0b2d6c22aa462a08d1154caba301117d32ea1c29ca65851f8a8/detection): 

> Matches rule PyInstaller by @bartblaze from ruleset PyInstaller at https://github.com/bartblaze/Yara-rules
Identifies executable converted using PyInstaller.

The Ruleset is this one : 
```
import "pe"
import "hash"
rule PyInstaller
{
meta:
	description = "Identifies executable converted using PyInstaller."
	author = "@bartblaze"
	date = "2020-01"
	tlp = "White"
	
strings:
	$ = "pyi-windows-manifest-filename" ascii wide
	$ = "pyi-runtime-tmpdir" ascii wide
	$ = "PyInstaller: " ascii wide

condition:
	uint16(0) == 0x5a4d and any of them or
	(
   for any i in (0..pe.number_of_resources - 1):
     (pe.resources[i].type == pe.RESOURCE_TYPE_ICON and
      hash.md5(pe.resources[i].offset, pe.resources[i].length) ==
      "20d36c0a435caad0ae75d3e5f474650c") //Default PyInstaller icon
	)
}
```

It causes [AstroSaveConverter](https://github.com/Tignus/AstroSaveConverter), an open-source project which anyone can see isn't a virus to be detected as one. Could you help with that ?

Thanks a lot

**Comment by bartblaze** [comment]
Please refer to https://github.com/bartblaze/Yara-rules/blob/master/README.md#help-a-generic-rule-is-hitting-my-software.

Additionally, Yara rules do not influence VirusTotal results. You will need to report any false positive to the antivirus vendor that detects your software.
