### ISSUE TITLE
AutoIt rules also match on AutoHotKey EXEs and scripts

### ISSUE THREAD

**Issue by recvfrom** [bartblaze/Yara-rules#4]
Hello!

It looks like `#NoTrayIcon` (ascii and wide) shows up in both AutoIt and AutoHotKey scripts...  Would you want to remove this string from the rules `AutoIT_Compiled` and `AutoIT_Script` so that the rules only match on AutoIt scripts?

Ex: https://www.virustotal.com/gui/file/91d42e3aedd39145cc0874c658d7358aff1c77b8e0cba9adab380149257e4e90/detection

https://analyze.intezer.com/analyses/7d01ed17-000a-41f3-9a4b-ffbeab2f5a14

```
$ python show-yara-matches.py bartblaze_autoit.yara 91d42e3aedd39145cc0874c658d7358aff1c77b8e0cba9adab380149257e4e90 
Processing matches for 91d42e3aedd39145cc0874c658d7358aff1c77b8e0cba9adab380149257e4e90
Matches for rule AutoIT_Script
    $ matched at 000a7744: 23 00 4E 00 6F 00 54 00 72 00 61 00 79 00 49 00 63 00 6F 00 6E 00
    $ matched at 000d8a91: 23 4E 6F 54 72 61 79 49 63 6F 6E
```

Thank you!

**Comment by bartblaze** [comment]
Hey Andrew - 100% agreed and great catch! Amended. Thank you! 😄

**Comment by recvfrom** [comment]
awesome, thanks @bartblaze!
