### ISSUE TITLE
help 

### ISSUE THREAD

**Issue by angelus65** [bartblaze/Yara-rules#6]
Hello friend, download the file yara rules master but I don't know how to use it, can you help me

**Comment by bartblaze** [comment]
Hi @angelus65! You'll need to do the following:

* Unzip the file so you have rules.yar
* Download Yara, see: https://github.com/bartblaze/Yara-rules#what-is-yara
* Now run Yara with the rules on your sample set like so:
`yara64.exe rules.yar <sample set> `

Good luck! 😄
