### ISSUE TITLE
ZLoader rule produces false positives

### ISSUE THREAD

**Issue by TETYYS** [bartblaze/Yara-rules#7]
It is usual for program to have strings `/post.php` and `Connection: close` in it, so ZLoader rule which requires only 2 of strings in its list to match, matches regular programs

https://github.com/bartblaze/Yara-rules/blob/4f329722c77e362d29d945a50420dedd641f8502/rules/crimeware/ZLoader.yar#L36

**Comment by bartblaze** [comment]
Hi tetyys - thank you - good point! Will tighten the rule.
