### ISSUE TITLE
Unable to create a fork

### ISSUE THREAD

**Issue by CCCS-MA** [bartblaze/Yara-rules#9]
Hello,

I'd like to create a PR to add more/correct some YARA rules that you have, but I'm unable to create a fork.

Is there a certain process for contribution?

**Comment by bartblaze** [comment]
Hi!

I haven't set any restrictions - so you should have no troubles forking, unless you're trying to create a private fork? 

If the latter, I suggest to have a look here for the options: https://gist.github.com/0xjac/85097472043b697ab57ba1b1c7530274

Looking forward to your PR! 😃

**Comment by CCCS-MA** [comment]
Apologies -- the reason I couldn't fork is because I already had a fork *face palm* apologies for the confusion!
